"""add image properties

Revision ID: 15609d8977d9
Revises: 3b8e682c563c
Create Date: 2023-05-08 22:17:38.590319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15609d8977d9'
down_revision = '3b8e682c563c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_delete', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('image_height', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('image_width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_width')
    op.drop_column('product', 'image_height')
    op.drop_column('product', 'image_delete')
    # ### end Alembic commands ###
