"""Cartproduct

Revision ID: 15abf735c9cb
Revises: a1db00c4ae10
Create Date: 2023-05-10 00:51:30.114376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15abf735c9cb'
down_revision = 'a1db00c4ae10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cart', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart'], ['cart.id'], name='cart_product_cart_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_product_pkey')
    )
    # ### end Alembic commands ###
