"""Cart

Revision ID: a1db00c4ae10
Revises: 15609d8977d9
Create Date: 2023-05-10 00:10:22.562770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1db00c4ae10'
down_revision = '15609d8977d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
