"""baseline

Revision ID: d8d8b5a9d60c
Revises: e9c4ae86cf0c
Create Date: 2023-04-24 00:56:18.347487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d8b5a9d60c'
down_revision = 'e9c4ae86cf0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
